// TODO: REPLACE THIS WITH YOUR COMPUTER'S LOCAL IP IF TESTING ON PHYSICAL DEVICE
// e.g. "http://192.168.1.5:8000"
// For Android Emulator, use "http://10.0.2.2:8000"
// For iOS Simulator, "http://localhost:8000" is fine.

export const getYouTubeTranscript = async (videoId: string): Promise<string | null> => {
    try {
        console.log(`[YouTube] Fetching transcript via Piped API for: ${videoId}`);

        // Piped API: https://docs.piped.video/docs/api-documentation/
        // Endpoint: /streams/{videoId}
        const pipedUrl = `https://pipedapi.kavin.rocks/streams/${videoId}`;

        const response = await fetch(pipedUrl);
        if (response.status !== 200) {
            console.error(`[YouTube] Piped API failed with status: ${response.status}`);
            return null;
        }

        const data = await response.json();

        if (!data.subtitles || data.subtitles.length === 0) {
            console.warn("[YouTube] No subtitles found via Piped.");
            return null;
        }

        // Find English track (prioritize manually created over auto-generated)
        const track = data.subtitles.find((t: any) => t.code === 'en' && !t.autoGenerated)
            || data.subtitles.find((t: any) => t.code === 'en')
            || data.subtitles[0];

        if (!track) {
            console.warn("[YouTube] No suitable subtitle track found.");
            return null;
        }

        console.log(`[YouTube] Found subtitle track: ${track.name} (${track.code}) - ${track.url}`);

        // Fetch the subtitle content
        const subtitleResponse = await fetch(track.url);
        const subtitleText = await subtitleResponse.text();

        // Piped usually returns text/vtt
        // Clean VTT
        const lines = subtitleText.split('\n');
        let transcript = "";

        lines.forEach(line => {
            // Basic VTT cleaning: skip headers, timestamps, empty lines
            if (
                line.startsWith('WEBVTT') ||
                line.includes('-->') ||
                line.trim().length === 0 ||
                /^\d+$/.test(line.trim()) // skip sequential numbers
            ) return;

            transcript += line.trim() + " ";
        });

        const fullText = transcript.replace(/\s+/g, ' ').trim();
        return fullText;

    } catch (err: any) {
        console.error("ERROR in getYouTubeTranscript:", err.message);
        return null;
    }
};

export const extractVideoId = (url: string): string | null => {
    const regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/;
    const match = url.match(regExp);
    return (match && match[2].length === 11) ? match[2] : null;
};
